trigger:
  branches:
    include: ['master']
  paths:
    include:
    - "v1/*.yml"
pr:
  branches:
    include:
    - master
  paths:
    include:
    - "v1/*.yml"
schedules:
- cron: "3 3 3 * *"
  displayName: Monthly Build
  branches:
    include:
    - master

stages:
 - stage: dummy
   jobs:
   - job: dummy
     pool:
       vmImage: 'ubuntu-16.04'
     steps:
     - checkout: self
