schedules:
- cron: "7 7 7 * *"
  displayName: Monthly Build
  branches:
    include:
    - master

stages:
 - stage: dummy
   jobs:
   - job: dummy
     pool:
       vmImage: 'ubuntu-16.04'
     steps:
     - checkout: self
