parameters:
  rustup_toolchain: 'stable'
jobs:
- job: check_formatting
  displayName: Check formatting
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: az-pipeline/unstable/rustup.yml
      parameters:
        rustup_toolchain: ${{ parameters.rustup_toolchain }}
        components:
          - rustfmt
    - script: |
        cargo fmt -- --check
      displayName: Run rustfmt
